/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileSlugRouteImport } from './routes/profile.$slug'
import { Route as MythbaseDirectRouteImport } from './routes/mythbase.direct'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as ApiPublicDodoWebhookRouteImport } from './routes/api/public/dodo-webhook'
import { Route as AuthenticatedCheckoutSuccessRouteImport } from './routes/_authenticated/checkout.success'
import { Route as AuthenticatedCheckoutCancelRouteImport } from './routes/_authenticated/checkout.cancel'
import { Route as AuthenticatedCheckoutPlanRouteImport } from './routes/_authenticated/checkout.$plan'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app/profile'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/app/integrations'
import { Route as AuthenticatedAppEmployeeIndexRouteImport } from './routes/_authenticated/app/$employee/index'
import { Route as AuthenticatedAppEmployeeThreadIdRouteImport } from './routes/_authenticated/app/$employee/$threadId'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSlugRoute = ProfileSlugRouteImport.update({
  id: '/profile/$slug',
  path: '/profile/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MythbaseDirectRoute = MythbaseDirectRouteImport.update({
  id: '/mythbase/direct',
  path: '/mythbase/direct',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDodoWebhookRoute = ApiPublicDodoWebhookRouteImport.update({
  id: '/api/public/dodo-webhook',
  path: '/api/public/dodo-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutSuccessRoute =
  AuthenticatedCheckoutSuccessRouteImport.update({
    id: '/checkout/success',
    path: '/checkout/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutCancelRoute =
  AuthenticatedCheckoutCancelRouteImport.update({
    id: '/checkout/cancel',
    path: '/checkout/cancel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutPlanRoute =
  AuthenticatedCheckoutPlanRouteImport.update({
    id: '/checkout/$plan',
    path: '/checkout/$plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/app/integrations',
    path: '/app/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEmployeeIndexRoute =
  AuthenticatedAppEmployeeIndexRouteImport.update({
    id: '/app/$employee/',
    path: '/app/$employee/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEmployeeThreadIdRoute =
  AuthenticatedAppEmployeeThreadIdRouteImport.update({
    id: '/app/$employee/$threadId',
    path: '/app/$employee/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/investors': typeof InvestorsRoute
  '/journey': typeof JourneyRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/vision': typeof VisionRoute
  '/api/chat': typeof ApiChatRoute
  '/mythbase/direct': typeof MythbaseDirectRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/checkout/$plan': typeof AuthenticatedCheckoutPlanRoute
  '/checkout/cancel': typeof AuthenticatedCheckoutCancelRoute
  '/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/$employee/$threadId': typeof AuthenticatedAppEmployeeThreadIdRoute
  '/app/$employee/': typeof AuthenticatedAppEmployeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/investors': typeof InvestorsRoute
  '/journey': typeof JourneyRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/vision': typeof VisionRoute
  '/api/chat': typeof ApiChatRoute
  '/mythbase/direct': typeof MythbaseDirectRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/checkout/$plan': typeof AuthenticatedCheckoutPlanRoute
  '/checkout/cancel': typeof AuthenticatedCheckoutCancelRoute
  '/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/$employee/$threadId': typeof AuthenticatedAppEmployeeThreadIdRoute
  '/app/$employee': typeof AuthenticatedAppEmployeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/investors': typeof InvestorsRoute
  '/journey': typeof JourneyRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/vision': typeof VisionRoute
  '/api/chat': typeof ApiChatRoute
  '/mythbase/direct': typeof MythbaseDirectRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/checkout/$plan': typeof AuthenticatedCheckoutPlanRoute
  '/_authenticated/checkout/cancel': typeof AuthenticatedCheckoutCancelRoute
  '/_authenticated/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/api/public/dodo-webhook': typeof ApiPublicDodoWebhookRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/$employee/$threadId': typeof AuthenticatedAppEmployeeThreadIdRoute
  '/_authenticated/app/$employee/': typeof AuthenticatedAppEmployeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/contact'
    | '/faq'
    | '/investors'
    | '/journey'
    | '/news'
    | '/sitemap.xml'
    | '/teams'
    | '/vision'
    | '/api/chat'
    | '/mythbase/direct'
    | '/profile/$slug'
    | '/app/integrations'
    | '/app/profile'
    | '/checkout/$plan'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/api/public/dodo-webhook'
    | '/app/'
    | '/app/$employee/$threadId'
    | '/app/$employee/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/contact'
    | '/faq'
    | '/investors'
    | '/journey'
    | '/news'
    | '/sitemap.xml'
    | '/teams'
    | '/vision'
    | '/api/chat'
    | '/mythbase/direct'
    | '/profile/$slug'
    | '/app/integrations'
    | '/app/profile'
    | '/checkout/$plan'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/api/public/dodo-webhook'
    | '/app'
    | '/app/$employee/$threadId'
    | '/app/$employee'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/contact'
    | '/faq'
    | '/investors'
    | '/journey'
    | '/news'
    | '/sitemap.xml'
    | '/teams'
    | '/vision'
    | '/api/chat'
    | '/mythbase/direct'
    | '/profile/$slug'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/profile'
    | '/_authenticated/checkout/$plan'
    | '/_authenticated/checkout/cancel'
    | '/_authenticated/checkout/success'
    | '/api/public/dodo-webhook'
    | '/_authenticated/app/'
    | '/_authenticated/app/$employee/$threadId'
    | '/_authenticated/app/$employee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InvestorsRoute: typeof InvestorsRoute
  JourneyRoute: typeof JourneyRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamsRoute: typeof TeamsRoute
  VisionRoute: typeof VisionRoute
  ApiChatRoute: typeof ApiChatRoute
  MythbaseDirectRoute: typeof MythbaseDirectRoute
  ProfileSlugRoute: typeof ProfileSlugRoute
  ApiPublicDodoWebhookRoute: typeof ApiPublicDodoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$slug': {
      id: '/profile/$slug'
      path: '/profile/$slug'
      fullPath: '/profile/$slug'
      preLoaderRoute: typeof ProfileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mythbase/direct': {
      id: '/mythbase/direct'
      path: '/mythbase/direct'
      fullPath: '/mythbase/direct'
      preLoaderRoute: typeof MythbaseDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/dodo-webhook': {
      id: '/api/public/dodo-webhook'
      path: '/api/public/dodo-webhook'
      fullPath: '/api/public/dodo-webhook'
      preLoaderRoute: typeof ApiPublicDodoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout/success': {
      id: '/_authenticated/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AuthenticatedCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/cancel': {
      id: '/_authenticated/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof AuthenticatedCheckoutCancelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/$plan': {
      id: '/_authenticated/checkout/$plan'
      path: '/checkout/$plan'
      fullPath: '/checkout/$plan'
      preLoaderRoute: typeof AuthenticatedCheckoutPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/app/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$employee/': {
      id: '/_authenticated/app/$employee/'
      path: '/app/$employee'
      fullPath: '/app/$employee/'
      preLoaderRoute: typeof AuthenticatedAppEmployeeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$employee/$threadId': {
      id: '/_authenticated/app/$employee/$threadId'
      path: '/app/$employee/$threadId'
      fullPath: '/app/$employee/$threadId'
      preLoaderRoute: typeof AuthenticatedAppEmployeeThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedCheckoutPlanRoute: typeof AuthenticatedCheckoutPlanRoute
  AuthenticatedCheckoutCancelRoute: typeof AuthenticatedCheckoutCancelRoute
  AuthenticatedCheckoutSuccessRoute: typeof AuthenticatedCheckoutSuccessRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppEmployeeThreadIdRoute: typeof AuthenticatedAppEmployeeThreadIdRoute
  AuthenticatedAppEmployeeIndexRoute: typeof AuthenticatedAppEmployeeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedCheckoutPlanRoute: AuthenticatedCheckoutPlanRoute,
  AuthenticatedCheckoutCancelRoute: AuthenticatedCheckoutCancelRoute,
  AuthenticatedCheckoutSuccessRoute: AuthenticatedCheckoutSuccessRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppEmployeeThreadIdRoute: AuthenticatedAppEmployeeThreadIdRoute,
  AuthenticatedAppEmployeeIndexRoute: AuthenticatedAppEmployeeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InvestorsRoute: InvestorsRoute,
  JourneyRoute: JourneyRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamsRoute: TeamsRoute,
  VisionRoute: VisionRoute,
  ApiChatRoute: ApiChatRoute,
  MythbaseDirectRoute: MythbaseDirectRoute,
  ProfileSlugRoute: ProfileSlugRoute,
  ApiPublicDodoWebhookRoute: ApiPublicDodoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
